"""
Django settings for papertrade project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from papertrade.config.base_dir import BASE_DIR
from dotenv import load_dotenv

load_dotenv()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tdr5dy665n6j7ur5678m4345345g345y34t534546h56h45gg3456345ty6j7ruy=gwr0w'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.users',
    'apps.utilities',

    'apps.broking',
    'apps.broking.authentication',
    'apps.broking.funds',
    'apps.broking.orders',
    'apps.broking.stock_exchange',

    "rest_framework",
    "rest_framework.authtoken",

    "crispy_forms",
    "crispy_bootstrap5",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


from .config.drf import *
from .config.db import *
from .config.routing import *
from .config.base_dir import *
from .config.project import *
from .config.authentication import *
from .config.templates import *

MARKET_HOLIDAYS = {  # %d-%b-%Y
    '26-Jan-2023',
    '18-Feb-2023',
    '07-Mar-2023',
    '30-Mar-2023',
    '04-Apr-2023',
    '07-Apr-2023',
    '14-Apr-2023',
    '22-Apr-2023',
    '01-May-2023',
    '05-May-2023',
    '28-Jun-2023',
    '29-Jul-2023',
    '15-Aug-2023',
    '16-Aug-2023',
    '19-Sep-2023',
    '28-Sep-2023',
    '02-Oct-2023',
    '24-Oct-2023',
    '14-Nov-2023',
    '27-Nov-2023',
    '25-Dec-2023',
}
SPECIAL_WORKING_HOURS = {
    '12-Nov-2023': {'from': '18:15', 'to': '19:15'}
}

