# Generated by Django 4.2 on 2023-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeapp',
            name='application_name',
            field=models.CharField(default='App', max_length=48),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='This can be asked as security question.', null=True),
        ),
    ]
