# Generated by Django 4.2 on 2023-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tradeapp_application_name_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeapp',
            name='access_key',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='tradeapp',
            name='access_secret',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='tradeapp',
            name='application_name',
            field=models.CharField(default='App', max_length=32),
        ),
    ]
