# Generated by Django 4.2 on 2023-04-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DematAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Summary of net Quantity of net transaction.')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broking.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text="Storing quantity as negative if its a 'SELL' order other vice store as positive.")),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock_exchange.demataccountentry', verbose_name='Transfer To Account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broking.symbol')),
            ],
        ),
    ]
