# Generated by Django 4.2 on 2023-04-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('stock_exchange', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
