# Generated by Django 4.2 on 2023-04-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
                ('exchange_type', models.CharField(blank=True, choices=[('EQUITY', 'Equity')], max_length=10, null=True)),
                ('order_type', models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market'), ('SL', 'SL'), ('SLM', 'SLM')], max_length=10)),
                ('product_type', models.CharField(choices=[('CNC', 'CNC'), ('MIS', 'Intraday'), ('NRML', 'Normal')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('validity', models.CharField(choices=[('DAY', 'Day'), ('IOC', 'IOC')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('limit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('is_amo', models.BooleanField(default=False)),
                ('algo_id', models.CharField(blank=True, help_text='(Optional) If User have any algo id for ref.', max_length=255, null=True)),
                ('order_placed_at', models.DateTimeField(auto_now_add=True)),
                ('basket_code', models.CharField(blank=True, help_text='User can create a unique basket id and sent the same for multiple orders.', max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('PROCESSING', 'PROCESSING AT BROKER / AMO'), ('OPEN', 'OPEN AT MARKET / AWAITING EXECUTION'), ('EXECUTED', 'EXECUTED IN MARKET'), ('REJECTED_BY_BROKER', 'REJECTED BY BROKER'), ('REJECTED_BY_EXCHANGE', 'REJECTED BY EXCHANGE'), ('CANCELLED', 'CANCELLED BY USER')], default='PROCESSING', max_length=20)),
                ('broker_error_message', models.DateTimeField(auto_now_add=True)),
                ('broker_id', models.CharField(blank=True, max_length=25, null=True)),
                ('exchange_error_message', models.DateTimeField(auto_now_add=True)),
                ('exchange_id', models.CharField(blank=True, max_length=25, null=True)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PROCESSING', 'PROCESSING AT BROKER / AMO'), ('OPEN', 'OPEN AT MARKET / AWAITING EXECUTION'), ('EXECUTED', 'EXECUTED IN MARKET'), ('REJECTED_BY_BROKER', 'REJECTED BY BROKER'), ('REJECTED_BY_EXCHANGE', 'REJECTED BY EXCHANGE'), ('CANCELLED', 'CANCELLED BY USER')], max_length=20)),
                ('new_status', models.CharField(choices=[('PROCESSING', 'PROCESSING AT BROKER / AMO'), ('OPEN', 'OPEN AT MARKET / AWAITING EXECUTION'), ('EXECUTED', 'EXECUTED IN MARKET'), ('REJECTED_BY_BROKER', 'REJECTED BY BROKER'), ('REJECTED_BY_EXCHANGE', 'REJECTED BY EXCHANGE'), ('CANCELLED', 'CANCELLED BY USER')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
