# Generated by Django 4.2 on 2023-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=40)),
                ('transaction_type', models.CharField(choices=[('PAY-IN', 'Account Recharge'), ('PAY-OUT', 'Payment to Bank Account'), ('TRADE-SELL', 'Income from Selling Securities'), ('TRADE-BUY', 'Outflow while Buying Securities')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
