name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build Stage: Run Django migrations and tests
      - name: Build the application
        run: |
          python manage.py migrate
          python manage.py test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          sudo docker build -t muhammednazil/paper-trade-broker:latest .

      - name: Push Docker image
        run: |
          sudo docker push muhammednazil/paper-trade-broker:latest

  deploy:
    needs: build
    runs-on: [self-hosted, linux]

    steps:
      - name: Deploy to AWS App Runner
        run: |
          aws apprunner update-service --service-name "CICD-selflearn" \
            --source-configuration ImageRepositoryType="ECR", ImageRepository={"ImageIdentifier=muhammednazil/paper-trade-broker:latest"} \
            --region ap-south-1

